### ISSUE TITLE
TypeError: unhashable type: 'dict' for untar_data for mnist_hello_world.ipynb on gradient

### ISSUE THREAD

**Issue by miwojc** [PacktPublishing/Deep-Learning-with-fastai-Cookbook#1]
@ryanmark1867 
I followed instructions from the book to set up gradient:
select gradient platform
create new notebook
select fastai as runtime
select Free-P5000
start notebook
launch jupyter notebook
open terminal and clone repo
validate_gradient_setup.ipynb works fine
open mnist_hello_world.ipynb
run entire notebook (Cell -> Run all)
full error message attached: 
![image](https://user-images.githubusercontent.com/32404415/129151498-26680e0b-dcce-4abb-9811-0ca03a53ec3c.png)

the same notebook works fine on colab.

**Comment by ryanmark1867** [comment]
Hi @miwojc - thanks for reporting your experience and providing detailed repro steps.

I just created a new Free-P5000 fastai Gradient instance and ran mnist_hello_world.ipynb, but I wasn't able to repro the issue that you saw. The untar_data cell where you saw the issue ran with no error in my new fastai instance:

![image](https://user-images.githubusercontent.com/39224115/129223582-7b89aee1-1b5b-4eae-a4b2-718eb038c1b6.png)


I noticed that there were some changes in the Gradient interface since the last time I set up an instance, which makes me think that there may have been some transient issue because of changes that Paperspace did recently. I'll look around some more to see if I can get any clues on why you saw the issue that you reported. Thanks - Mark

**Comment by miwojc** [comment]
I have run the code again on gradient and it run fine. Not sure what was causing the issue the first time. The first time i have tried and replicated the issue. But now i haven't changed anything and it run fine.

**Comment by miwojc** [comment]
Also i wonder if there is a need to pip install fastbook in every notebook on gradient. Once it's installed in gradient environment it is not needed to do it every time?

**Comment by miwojc** [comment]
Can we use this issue for my feedback on the book? Let me know if there's more appropriate place for that?

I learnt from the book how to install jupyter lab on gradient which is great. Thank you. Then then book provides resources to enable debugger in lab. However i think there is a lot easier way to do it: simply by updating ipykernel to version 6 enables debugger in lab: pip install ipykernel==6 (process is similar to installing jupyterlab on gradient)

**Comment by ryanmark1867** [comment]
Hi @miwojc - thanks for confirming that the issue has gone away. Gradient is overall a better platform for exploring fastai than Colab. Colab requires too much fiddling every time you want to use it, and the integration between Colab and Drive can be confusing, particularly for somebody who is a beginner. That being said, Paperspace makes changes to Gradient on a fairly regular basis, and while it is quite stable now, there are still some transient issues. 

Good point about pip installing fastbook - it's not strictly necessary, but I can't be guaranteed that the reader will run the code examples in order. Some readers may skip right to chapter 3, or, if they don't care about tabular data, skip to chapter 4, 5, or 6, so I need to assume that every code example can run correctly even if it's the first example that somebody runs.

Thanks for the debugger suggestion - it's too late now to make changes to the text to incorporate a different (simpler) method to set up a debugger in JupyterLab, but if I get the opportunity to make further changes, I will incorporate this suggestion.

**Comment by miwojc** [comment]
Hi Mark,
I think fastai now uses fastdownload to download and unzip data. when i run notebook from chapter 3: accessing_non_curated_datasets.ipynb i get error: `NameError: name 'file_extract' is not defined`
in this commit Jeremy introduces the fastdownload: https://github.com/fastai/fastai/commit/63b624c696c956a850cc137878d2582402c1db92#diff-f4e010d8a6881acfe4c75b1a75a3b9bb3f330bfc9c726dfffc7008b09f4b4065

i think file_extract function definition was removed:
```python
def file_extract(fname, dest=None):
    "Extract `fname` to `dest` using `tarfile` or `zipfile`."
    if dest is None: dest = Path(fname).parent
    fname = str(fname)
    if   fname.endswith('gz'):  tarfile.open(fname, 'r:gz').extractall(dest)
    elif fname.endswith('zip'): zipfile.ZipFile(fname     ).extractall(dest)
    else: raise Exception(f'Unrecognized archive: {fname}')
```

when i define above function in the notebook it works. but without explicit definition it returns an error.

Also in the same notebook we put kaggle api key unprotected in raw text in notebook, on gradient the notebooks are publicly available. is there a way to provide kaggle api key in a safe / protected way? Thank you!

**Comment by ryanmark1867** [comment]
Hi @miwojc  - thanks on both counts (the regression in fastai re. file_extract and the kaggle key being public). I was able to repro the issue you reported with file_extract, and with the explicit definition you suggested the code works again. 

I wasn't able to find documentation for fastdownload and a naive attempt to use it failed for me, so I will go the file_extract function route.

For the Kaggle key, I had a placeholder which I must have replaced with my own credentials in one of the code updates. I'll put the placeholder back and the code will match the book again: 

![image](https://user-images.githubusercontent.com/39224115/129639858-4dc56088-67f9-4052-8777-b94cc501779d.png)


Thanks again for reporting these issues - much appreciated!

**Comment by ryanmark1867** [comment]
Issue corrected with "cleanup kaggle issues".
